### ISSUE TITLE
Organization clean-up

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scala-subscript/subscript#15]
As for now, the following repositories are in use in scala-subscript organization:
- subscript
- examples
- eye-test
- scala-subscript.github.io - documentation to be hosted here
- subscript-filedownloader-example - to be integrated in `examples` repo

I propose to remove all the other remaining repos from the organization so that they don't clutter the repos page.

**Comment by AndreVanDelft** [comment]
Yes, good idea. Maybe it is good to keep a local copy, in case we need to track the history.

**Comment by anatoliykmetyuk** [comment]
I've cleaned up the old repositories. If ever a need in them arises, I made a backup copy and uploaded it to Google Drive: https://drive.google.com/file/d/0B5Ico8WIT2spbDVRVDNhS0toRzQ/view?usp=sharing
