### ISSUE TITLE
Tiny code fragments reset script's result value to `null`

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scala-subscript/subscript#18]
Here:

``` scala
s = ^1 {::}
```

The result of `s` is `null`.

Expected behaviour is that the result should be `Success(1)`. Like in:

``` scala
s = ^1 {!!}
```

(works correctly).

**Comment by AndreVanDelft** [comment]
Indeed, since there is 1 term, `^1`, that specifies the setting of the result value, that term should prevail.
