### ISSUE TITLE
Clean up swing scripts

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/subscript#20]
```
mouseReleased    (comp: Component, ?p : java.awt.Point) = var mre: MouseReleased=null
                                                          event(   MouseReleasedReactor[Any,N_code_eventhandling[Any]](comp), ?mre ) // TBD: ...
                                                          { p=mre.point }

/* these 4 scripts should become:
  ...
  mouseReleased    (comp: Component, ?p : java.awt.Point) = var mre: MouseReleased=null; event(MouseReleasedReactor[Any,N_code_eventhandling[Any]](comp   ), ?mre); {! p=mre.point !}
for now:
error: missing parameter type for expanded function ((x$4) => _mce.at(here).value = x$4)
mouseClicks(n:Int,comp: Component, ?p : java.awt.Point) = var mce: MouseClicked =null; event( MouseClickedReactor[Any,N_code_eventhandling[Any]](comp, n), ?mce); {! p=mce.point !}
                                                                                                                                                 ^
  */
```

I have forgotten what the issue was, but anyway I don't see much difference between the two versions of mouseReleased.
Except the code fragment at the end.
Currently it is `{ p=mre.point }`.
However, that is not a real code fragment. It is Scala code that syntactically requires an implicit conversion. AFAIK there is no such conversion in scope, so this should not compile.
How come?

When this has been sorted out, the code fragment should become `{: p=mre.point :}`

**Comment by anatoliykmetyuk** [comment]
`{a = b}` is an assignment of type Unit. Unit is converted to tiny code fragments by the maybeCall macro - to support method calls in script call positions  So the semantics is the same as {:a = b:}

**Comment by AndreVanDelft** [comment]
I am "afraid" that makes sense.
Good to know, and to make these kind of things explicit in our documentation.
