### ISSUE TITLE
Various compile & runtime errors in AboutIteration koan

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/subscript#34]
E.g. when compiling koan 1:

> test-only PathToEnlightenment
> [trace] Stack trace suppressed: run last test:managedSources for the full output.
> [error](test:managedSources) java.lang.ArrayIndexOutOfBoundsException: 237
> [error] Total time: 9 s, completed 12-feb-2016 3:18:42

And in koan 5:

```
s = b c d / ..?
test(3) {runWithInput(s)(b,b        ); thenActivatedOrSuccess(__`b,c`)}
```

> Test 3: Set(b) did not contain only (b, c) (OperatorKoansHelper.scala:46)

**Comment by AndreVanDelft** [comment]
The problems are probably all in the koan source file.
Only the preprocessor error messages are quite bad.

**Comment by anatoliykmetyuk** [comment]
> java.lang.ArrayIndexOutOfBoundsException: 237

This indicates a syntactic error and comes from a parser, most probably. I'll look at it a bit later, currently working on the `?if` syntax.

**Comment by AndreVanDelft** [comment]
Don't waste too much time on that error;
Parboiled just gives bad error messages, and we will move away from it.

**Comment by anatoliykmetyuk** [comment]
I meant I look at the koan file. I agree, it is hardly possible to improve the error messaging significantly with our current framework stack.

**Comment by AndreVanDelft** [comment]
I am afraid I don't know any more how I got the problems.
Probably missing braces at the end of `test(1)` lines etc. 
The version with the outcommented code had a lot of such errors.
