### ISSUE TITLE
Dataflow operators should stack

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scala-subscript/subscript#4]
So far, expressions like `a ~~(x: T)~~> b ~~(y: T)~~> c` are not possible. Parsing fails at second dataflow.

**Comment by anatoliykmetyuk** [comment]
Should `a ~~> b ~~> c` be `a ~~> [b ~~> c]` or `[a ~~> b] ~~> c`?

**Comment by AndreVanDelft** [comment]
`[a ~~> b] ~~> c` is most natural; see `10 - 1 - 2`.
A special case is when the last arrow is an exception flow. What would we expect of:
`a ~~> b ~/~> c`
IMO indeed the left-association would be convenient.

**Comment by anatoliykmetyuk** [comment]
What's `10-1-2`? Just thought about it: rhs associativity grants the best visibility for the leftmost operator. [Use case](https://github.com/scala-subscript/eye-test/blob/master/src/main/scala/eyetest/app/Login.scala#L75):

``` scala
             {!getCurrentUser!} ~~(currentUser: String)~~> [
               [repositories.score.last: currentUser ~~(Some((right: Double, left: Double, _)))~~> (new Test(currentUser, right, left, 5))
                                                    +~~(None                                  )~~> (new Test(currentUser, 20   , 20  , 5))]
               ~~((right: Double, left: Double))~~> [
                 repositories.score.write: currentUser, (right, left)
                 (new Result(right, left))
               ]
             ]
```

Three dataflows here, all right-associative, so that `currentUser` from the first dataflow can be used even in the last dataflow.

`a ~~> b ~/~> c` will be parsed as one dataflow, `c` belongs to `a`'s failure, because the longest match is parsed.

**Edit**: Second dataflow of the example is left associative though.

**Comment by AndreVanDelft** [comment]
10 - 1 - 2 = 7, not 11.

**Comment by anatoliykmetyuk** [comment]
Dataflow is a special case IMO.

``` scala
scala> classOf[Int => Int => Int]
res0: Class[Int => (Int => Int)] = interface scala.Function1
```

**Comment by AndreVanDelft** [comment]
Yes, I am convinced now that right-associativity is the best choice. The use case is great.
I recall that about a half year ago I had the same visibility argument in mind, but I forgot it.
